autoconf-2.72.tar.gz:
  size: 2143794
  object_id: dc4212d5-5725-4f1b-7a6d-f28302fe2352
  sha: sha256:afb181a76e1ee72832f6581c0eddf8df032b83e2e0239ef79ebedc4467d92d6e
automake/automake-1.17.tar.gz:
  size: 2451070
  object_id: 5e8a7eea-388b-4e4b-4a8d-d8dee57a06fb
  sha: sha256:397767d4db3018dd4440825b60c64258b636eaf6bf99ac8b0897f06c89310acd
cifs-utils-7.0.tar.bz2:
  size: 418638
  object_id: 96fdc4b7-9cb6-44cf-59db-acc3421c943e
  sha: sha256:0defaab85bd3ea46ffc45ab41fb0d0ad54d05ae2cfaa7e503de86d4f12bc8161
cifs-utils/cifs-utils-7.1.tar.bz2:
  size: 423114
  object_id: 097d49f2-85f8-45d0-6d9e-d01ef7dbd613
  sha: sha256:a21123f76a4a6a36c9653189ba4918ebdf3cfcd3f9092730a47ff3450b5b5b2a
keyutils-1.6.3.tar.gz:
  size: 753599
  object_id: f0f4ab30-4153-4b18-6d85-705bf9ec197d
  sha: sha256:19d627905a4f81da319faa429b42c1000edfda0858b35890c484d91b8af3bd39
libtool/libtool-2.4.7.tar.gz:
  size: 1938886
  object_id: 8b2d0b98-0404-4be4-56ec-7e1f335e8102
  sha: sha256:04e96c2404ea70c590c546eba4202a4e12722c640016c12b9b2f1ce3d481e9a8
pkg-config-0.29.2.tar.gz:
  size: 2016830
  object_id: 17b48507-5868-4826-43ba-14ee1c063907
  sha: 76e501663b29cb7580245720edfb6106164fad2b
talloc-2.4.2.tar.gz:
  size: 679750
  object_id: c0648370-92fa-4be0-73e3-b5c6489e2c72
  sha: sha256:85ecf9e465e20f98f9950a52e9a411e14320bc555fa257d87697b7e7a9b1d8a6
