autoconf-2.69.tar.gz:
  size: 1927468
  object_id: f26ccc89-cac6-4ab2-42c6-394b6d8911af
  sha: 562471cbcb0dd0fa42a76665acf0dbb68479b78a
automake-1.15.tar.gz:
  size: 2244206
  object_id: c36c457b-640d-4f34-73dd-da239db8d2fd
  sha: b5a840c7ec4321e78fdc9472e476263fa6614ca1
cifs-utils-6.7.tar.bz2:
  size: 363647
  object_id: f76fd32c-1c75-4c28-49fd-48ba34a43204
  sha: 9ba5091d7c2418a90773c861f04a3f4a36854c14
libtool-2.4.6.tar.gz:
  size: 1806697
  object_id: 4c24395e-816f-4d5d-7369-6d5d5fa5741d
  sha: 25b6931265230a06f0fc2146df64c04e5ae6ec33
pkg-config-0.29.2.tar.gz:
  size: 2016830
  object_id: 17b48507-5868-4826-43ba-14ee1c063907
  sha: 76e501663b29cb7580245720edfb6106164fad2b
talloc-2.1.9.tar.gz:
  size: 440335
  object_id: b65fd9d0-6fb6-4d66-68af-e11fc2d8efd2
  sha: e1e79fec4c0b6bd92be904a9c03b0a168478711a
